/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.1.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("org.jetbrains.kotlin.jvm").version("1.8.20")
    id("dev.adamko.dokkatoo-html") version "1.3.0"
}


dependencies {
    dokkatoo(project(":module-1"))
    dokkatoo(project(":module-2"))
}